<?php
/**
 * TL_ROOT/system/modules/changelanguage/languages/lv/modules.php 
 * 
 * Contao extension: changelanguage 2.2.0 stable 
 * Latvian translation file 
 * 
 * Copyright : © 2008-2012 terminal42 gmbh, © 2008 Felix Pfeiffer 
 * License   : LGPL 
 * Author    : terminal42 gmbh (terminal42), http://www.terminal42.ch/ 
 * Translator: Maris Celmins (warrior), http://maris.celmins.lv 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['changelanguage']['0'] = "Mainīt valodu";
$GLOBALS['TL_LANG']['FMD']['changelanguage']['0'] = "Mainīt valodu";
$GLOBALS['TL_LANG']['FMD']['changelanguage']['1'] = "Šis modulis ļauj jums pārslēgties starp dažādām valodām lapā.";
$GLOBALS['TL_LANG']['FMD']['languageRedirect']['0'] = "Novirzīt uz dalībnieka valodu";
$GLOBALS['TL_LANG']['FMD']['languageRedirect']['1'] = "Šis modulis novirza apmeklētāju uz lapu, izmantojot dalībnieka konfigurēto valodu.";
 
?>
