<?php
/**
 * TL_ROOT/system/modules/changelanguage/languages/lv/tl_module.php 
 * 
 * Contao extension: changelanguage 2.2.0 stable 
 * Latvian translation file 
 * 
 * Copyright : © 2008-2012 terminal42 gmbh, © 2008 Felix Pfeiffer 
 * License   : LGPL 
 * Author    : terminal42 gmbh (terminal42), http://www.terminal42.ch/ 
 * Translator: Maris Celmins (warrior), http://maris.celmins.lv 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['hideActiveLanguage']['0'] = "Slēpt aktīvo valodu";
$GLOBALS['TL_LANG']['tl_module']['hideNoFallback']['0'] = "Slēpt valodas bez tiešas atkāpšanās";
$GLOBALS['TL_LANG']['tl_module']['keepUrlParams']['0'] = "Saglabāt URL parametrus";
$GLOBALS['TL_LANG']['tl_module']['customLanguage']['0'] = "Pielāgoti valodu teksti";
$GLOBALS['TL_LANG']['tl_module']['customLanguageText']['1'] = "Lūdzu, ievadiet saturu nomainīšanai visās valodās. Izmanto mazos burtus īsceļus.";
$GLOBALS['TL_LANG']['tl_module']['opValue'] = "Valodas īsceļš";
$GLOBALS['TL_LANG']['tl_module']['opLabel'] = "Aizstājējteksts";
 
?>
