<?php
/**
 * TL_ROOT/system/modules/changelanguage/languages/lv/tl_page.php 
 * 
 * Contao extension: changelanguage 2.2.0 stable 
 * Latvian translation file 
 * 
 * Copyright : © 2008-2012 terminal42 gmbh, © 2008 Felix Pfeiffer 
 * License   : LGPL 
 * Author    : terminal42 gmbh (terminal42), http://www.terminal42.ch/ 
 * Translator: Maris Celmins (warrior), http://maris.celmins.lv 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_page']['languageMain']['0'] = "Fallback-Page";
$GLOBALS['TL_LANG']['tl_page']['languageRoot']['0'] = "Ārvalstu domēna saknes lapa";
$GLOBALS['TL_LANG']['tl_page']['no_subpage'] = "Nav vienādu lapu";
$GLOBALS['TL_LANG']['tl_page']['no_rootpage'] = "Šī ir pamatvaloda saknes vietnē";
 
?>
