<?php
/**
 * TL_ROOT/system/modules/changelanguage/languages/cs/default.php 
 * 
 * Contao extension: changelanguage 2.1.1 stable 
 * Tschechisch translation file 
 * 
 * Copyright : © 2008-2012 terminal42 gmbh, © 2008 Felix Pfeiffer 
 * License   : LGPL 
 * Author    : terminal42 gmbh (terminal42), http://www.terminal42.ch/ 
 * Translator: Jan Kout (jenda), www.jankout.eu 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MSC']['noMainLanguage'] = "Chybí hlavní jazyk";
 
?>
