<?php
/**
 * TL_ROOT/system/modules/changelanguage/languages/cs/modules.php 
 * 
 * Contao extension: changelanguage 2.1.1 stable 
 * Tschechisch translation file 
 * 
 * Copyright : © 2008-2012 terminal42 gmbh, © 2008 Felix Pfeiffer 
 * License   : LGPL 
 * Author    : terminal42 gmbh (terminal42), http://www.terminal42.ch/ 
 * Translator: Jan Kout (jenda), www.jankout.eu 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['changelanguage']['0'] = "Měnič jazyků";
$GLOBALS['TL_LANG']['FMD']['changelanguage']['0'] = "Měnič jazyků";
$GLOBALS['TL_LANG']['FMD']['changelanguage']['1'] = "Tento modul umožní přepínat mezi jazykovými verzemi jednotlivých stránek. ";
$GLOBALS['TL_LANG']['FMD']['languageRedirect']['0'] = "Přesměrovat na jazyk uživatele";
$GLOBALS['TL_LANG']['FMD']['languageRedirect']['1'] = "Tento modul přesměruje návštěvníky na stránku, která používá jazyk uživatele, který je vybraný v nastavení jeho profilu.";
 
?>
