<?php
/**
 * TL_ROOT/system/modules/changelanguage/languages/cs/tl_module.php 
 * 
 * Contao extension: changelanguage 2.1.1 stable 
 * Tschechisch translation file 
 * 
 * Copyright : © 2008-2012 terminal42 gmbh, © 2008 Felix Pfeiffer 
 * License   : LGPL 
 * Author    : terminal42 gmbh (terminal42), http://www.terminal42.ch/ 
 * Translator: Jan Kout (jenda), www.jankout.eu 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['hideActiveLanguage']['0'] = "Skrýt aktivní jazyk";
$GLOBALS['TL_LANG']['tl_module']['hideActiveLanguage']['1'] = "Vyberte prosím tuto možnost, pokud chcete skrýt aktivní jazyk dané stránky.";
$GLOBALS['TL_LANG']['tl_module']['hideNoFallback']['0'] = "Skrýt jazyky bez přímého jazykového zrcadlení";
$GLOBALS['TL_LANG']['tl_module']['hideNoFallback']['1'] = "Nezobrazit jazyky, k nimž se nevztahuje žádná jiná jazyková verze.";
$GLOBALS['TL_LANG']['tl_module']['keepUrlParams']['0'] = "Zachovat kritéria URL";
$GLOBALS['TL_LANG']['tl_module']['keepUrlParams']['1'] = "Vyberte prosím tuto možnost, pokud chcete zachovat parametry URL, až přepnete na zrcadlící se jazykovou verzi.";
$GLOBALS['TL_LANG']['tl_module']['customLanguage']['0'] = "Vlastní texty k vybraným jazykům";
$GLOBALS['TL_LANG']['tl_module']['customLanguage']['1'] = "Zvolte prosím tuto možnost, pokud chcete zadat vlastní pojmenování vybraných jazyků (žádné jazykové zkratky). Tato možnost nebude brána na vědomí, pokud jste zvolili, aby se zobrazovaly vlajky pro dané jazyky.";
$GLOBALS['TL_LANG']['tl_module']['customLanguageText']['1'] = "Zadejte prosím náhradní text pro jednotlivé jazyky. Použijte prosím malá písmenka.";
$GLOBALS['TL_LANG']['tl_module']['opValue'] = "Jazyková zkratka";
$GLOBALS['TL_LANG']['tl_module']['opLabel'] = "Náhradní text";
 
?>
