<?php
/**
 * TL_ROOT/system/modules/changelanguage/languages/cs/tl_page.php 
 * 
 * Contao extension: changelanguage 2.1.1 stable 
 * Tschechisch translation file 
 * 
 * Copyright : © 2008-2012 terminal42 gmbh, © 2008 Felix Pfeiffer 
 * License   : LGPL 
 * Author    : terminal42 gmbh (terminal42), http://www.terminal42.ch/ 
 * Translator: Jan Kout (jenda), www.jankout.eu 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_page']['languageMain']['0'] = "Zrcadlící se stránka v jiné jazykové verzi";
$GLOBALS['TL_LANG']['tl_page']['languageMain']['1'] = "Vyberte stránku v jiném jazyce, která náleží k této stránce. ";
$GLOBALS['TL_LANG']['tl_page']['languageRoot']['0'] = "Cizí doména pro hlavní jazyk";
$GLOBALS['TL_LANG']['tl_page']['languageRoot']['1'] = "Vyberte prosím, zda tato struktura stránky patří k jazyku jiné domény.";
$GLOBALS['TL_LANG']['tl_page']['no_subpage'] = "Žádná rovnocenná stránka";
$GLOBALS['TL_LANG']['tl_page']['no_rootpage'] = "Toto je hlavní doména";
 
?>
