<?php
/**
 * TL_ROOT/system/modules/changelanguage/languages/fa/modules.php 
 * 
 * Contao extension: changelanguage 2.2.1 stable 
 * Persian translation file 
 * 
 * Copyright : © 2008-2012 terminal42 gmbh, © 2008 Felix Pfeiffer 
 * License   : LGPL 
 * Author    : terminal42 gmbh (terminal42), http://www.terminal42.ch/ 
 * Translator: Hamid Abbaszadeh (respinar), http://contao.ir/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['changelanguage']['0'] = "تغییر زبان";
$GLOBALS['TL_LANG']['FMD']['changelanguage']['0'] = "تغییر زبان";
 
?>
