<?php
/**
 * TL_ROOT/system/modules/changelanguage/languages/ja/modules.php 
 * 
 * Contao extension: changelanguage 2.2.4 
 * Japanese translation file 
 * 
 * Copyright : © 2008-2014 terminal42 gmbh, © 2008 Felix Pfeiffer 
 * License   : LGPL-3.0+ 
 * Author    : terminal42 gmbh (terminal42), http://www.terminal42.ch/ 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['changelanguage']['0'] = "言語の変更";
$GLOBALS['TL_LANG']['FMD']['changelanguage']['0'] = "言語の変更";
$GLOBALS['TL_LANG']['FMD']['changelanguage']['1'] = "このモジュールは異なる言語のページにに切り替えをできるようにします。";
$GLOBALS['TL_LANG']['FMD']['languageRedirect']['0'] = "メンバーの言語に移動";
$GLOBALS['TL_LANG']['FMD']['languageRedirect']['1'] = "このモジュールはメンバーが設定した言語を使用したページに移動します。";
 
?>
