<?php
/**
 * TL_ROOT/system/modules/changelanguage/languages/ja/tl_module.php 
 * 
 * Contao extension: changelanguage 2.2.4 
 * Japanese translation file 
 * 
 * Copyright : © 2008-2014 terminal42 gmbh, © 2008 Felix Pfeiffer 
 * License   : LGPL-3.0+ 
 * Author    : terminal42 gmbh (terminal42), http://www.terminal42.ch/ 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['hideActiveLanguage']['0'] = "現在の言語を表示しない";
$GLOBALS['TL_LANG']['tl_module']['hideActiveLanguage']['1'] = "現在ウェブサイトの表示に使用している言語を表示したくない場合に選択してください。";
$GLOBALS['TL_LANG']['tl_module']['hideNoFallback']['0'] = "直接の代替がない言語を非表示";
$GLOBALS['TL_LANG']['tl_module']['hideNoFallback']['1'] = "直接代替を割り当てていない言語を表示しません。";
$GLOBALS['TL_LANG']['tl_module']['keepUrlParams']['0'] = "URLのパラメーターを保持";
$GLOBALS['TL_LANG']['tl_module']['keepUrlParams']['1'] = "言語を切り替えるときに、URLのパラメーターをそのまま保持したい場合に選択してください。";
$GLOBALS['TL_LANG']['tl_module']['customLanguage']['0'] = "言語の文字列をカスタマイズ";
$GLOBALS['TL_LANG']['tl_module']['customLanguage']['1'] = "(大文字の言語のショートカットの代わりに)カスタマイズした文字列を言語に使用したい場合に選択してください。";
$GLOBALS['TL_LANG']['tl_module']['customLanguageText']['1'] = "小文字のショートカットを使用してください。各言語を表す文字列を入力してください。";
$GLOBALS['TL_LANG']['tl_module']['opValue'] = "言語のショートカット";
$GLOBALS['TL_LANG']['tl_module']['opLabel'] = "言語の文字列";
 
?>
